BASH_PROFILE_LOADED=true

# Get the aliases and functions if not loaded yet
if [ -z $BASHRC_LOADED ] && [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
pathmunge /usr/local/bin
# this is ruby 1.8.2 -- pathmunge /usr/local/ruby/bin before
pathmunge /usr/local/mysql/bin
pathmunge $HOME/bin
pathmunge /usr/local/ant/bin
pathmunge /opt/local/bin
pathmunge /usr/local/jalopy
pathmunge /usr/local/Trolltech/Qt-4.3.4/bin
pathmunge /usr/local/pmd/bin
pathmunge /usr/local/groovy/bin
pathmunge /usr/local/maven/bin
pathmunge /usr/local/git/bin
test -r /sw/bin/init.sh && . /sw/bin/init.sh

