#!/bin/bash



cpmunge () {
        if ! echo $CP | /usr/bin/egrep -q "(^|:)$1($|:)" ; then
           if [ "$2" = "after" ] ; then
              CP=$CP:$1
           else
              CP=$1:$CP
           fi
        fi
}

addjars () {
    for thejar in $1/*.jar
      do
      if [ -f "$thejar" ]; then
          cpmunge "$thejar"
      fi
    done
}

addjars lib
cpmunge build/classes

if [ $# == 1 ] ; then
    prog=$1
    shift
else
    prog=org.six11.resize.Main
fi
# java -Xms<initial heap size> -Xmx<maximum heap size>
java -Xms64m -Xmx512m -classpath $CP $prog $@
